@startuml

title: 自动更新七牛证书
start
repeat
    if (获取域名信息) then (成功)
        if (判断是否为 HTTPS) then (是)
            :获取 CertID;
            if (获取证书信息, 并判断是否会在30天内过期) then (是)
                :获取证书;
                partition 获取证书 {
                    if (加载本地证书缓存) then (成功)
                        if (更新证书) then (失败)
                            :获取新证书;
                        else (成功)
                        endif
                        :保存证书缓存;
                    else (失败)
                        :获取新证书;
                        :保存证书缓存;
                    endif
                }
                :上传证书;
                :修改域名证书;
                :删除旧的证书;
            else (否)
                :继续循环;
            endif
        else (否)
            :获取证书;
            :上传证书;
            :升级域名为 HTTPS;
        endif
    else (失败)
        :退出程序;
        stop
    endif
repeat while (三小时后)
stop

@enduml